//! The document a consumer hands in to say which slice of the game it wants.

use serde::Deserialize;
use std::collections::BTreeMap;

/// Which slice of the game a consumer wants, and what to call it.
///
/// Every name in here belongs to the caller. FactorioTools wants ten entity
/// names that are exactly its planner's list; a blueprint editor wants
/// hundreds; a map tool wants none of them. Baking any of them into this crate
/// would make it one consumer's tool with extra steps.
///
/// Unknown keys are rejected. A misspelled allowlist would otherwise produce a
/// fixture quietly missing whatever the caller asked for.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TrimSpec {
    /// Written to the output as `_comment`. Usually "do not hand-edit".
    #[serde(default)]
    pub comment: Option<String>,
    /// Prototype names to look up, by name rather than by type.
    pub entities: Vec<String>,
    /// Prototype fields worth pinning. A field absent on a given prototype is
    /// skipped, so one flat list covers every type.
    #[serde(default)]
    pub entity_fields: Vec<String>,
    /// Fluid box connection keys worth keeping. Everything else on a connection
    /// is graphics: `pipe_covers` alone is several hundred lines of sprite
    /// definitions per entity.
    #[serde(default)]
    pub connection_fields: Vec<String>,
    /// Which fluid boxes to look inside, for example `output_fluid_box`.
    #[serde(default)]
    pub fluid_boxes: Vec<String>,
    /// Output key to prototype type. Emits the sorted names of every prototype
    /// of that type, which is how FactorioTools pins the module list.
    #[serde(default)]
    pub name_lists: BTreeMap<String, String>,
    /// Output key to `defines` table name. The game calls it `direction`;
    /// FactorioTools' fixture calls the result `directions`.
    #[serde(default)]
    pub defines: BTreeMap<String, String>,
    /// Whether to read the game's migration files into a rename table.
    #[serde(default)]
    pub include_renames: bool,
    /// Where `defines` values come from.
    ///
    /// `doc-index` reads `order` out of `runtime-api.json`, which is a
    /// documentation index rather than the runtime value. It is right only
    /// while a table is a dense sequence from zero. `probe` reads the value the
    /// running game uses, and needs a `create` run's dump.
    ///
    /// The default is `doc-index` so existing callers keep working. New callers
    /// should choose `probe`. See FactorioTools#83.
    #[serde(default)]
    pub defines_from: DefinesSource,
}

/// Where defines values are read from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum DefinesSource {
    /// `order` from `runtime-api.json`. An inference, not a reading.
    #[default]
    DocIndex,
    /// The value the running game reports, via a `create` probe.
    Probe,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deserialises_the_factoriotools_shape() {
        let json = r#"{
            "comment": "Generated by a tool. Do not hand-edit.",
            "entities": ["pumpjack", "beacon"],
            "entity_fields": ["collision_box", "module_slots"],
            "connection_fields": ["position", "flow_direction"],
            "fluid_boxes": ["fluid_box", "output_fluid_box"],
            "name_lists": { "modules": "module" },
            "defines": { "directions": "direction" },
            "include_renames": true
        }"#;
        let spec: TrimSpec = serde_json::from_str(json).unwrap();
        assert_eq!(
            spec.comment.as_deref(),
            Some("Generated by a tool. Do not hand-edit.")
        );
        assert_eq!(spec.entities, vec!["pumpjack", "beacon"]);
        assert_eq!(spec.fluid_boxes.len(), 2);
        assert_eq!(spec.name_lists.get("modules").unwrap(), "module");
        assert_eq!(spec.defines.get("directions").unwrap(), "direction");
        assert!(spec.include_renames);
    }

    #[test]
    fn everything_except_entities_has_a_default() {
        // A caller that wants only entity geometry should not have to write six
        // empty lists to say so.
        let spec: TrimSpec = serde_json::from_str(r#"{ "entities": ["pipe"] }"#).unwrap();
        assert!(spec.comment.is_none());
        assert!(spec.entity_fields.is_empty());
        assert!(spec.name_lists.is_empty());
        assert!(!spec.include_renames);
    }

    #[test]
    fn an_unknown_key_is_rejected_rather_than_ignored() {
        // A typo in an allowlist name would otherwise silently produce a fixture
        // missing the field the caller asked for, which is the failure this
        // whole tool exists to prevent.
        let json = r#"{ "entities": ["pipe"], "entity_feilds": ["collision_box"] }"#;
        assert!(serde_json::from_str::<TrimSpec>(json).is_err());
    }

    #[test]
    fn the_output_key_is_the_callers_choice_not_the_games() {
        // The game calls it `direction`; FactorioTools' fixture calls it
        // `directions`. Neither name belongs to this crate.
        let spec: TrimSpec =
            serde_json::from_str(r#"{ "entities": [], "defines": { "whatever": "direction" } }"#)
                .unwrap();
        assert_eq!(spec.defines.get("whatever").unwrap(), "direction");
    }
}
